<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>x64</Platforms>
    <OutputType>Exe</OutputType>
    <RootNamespace>Finalspace.Onigiri</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject>Finalspace.Onigiri.Program</StartupObject>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>..\Build\OnigiriConsole\x64-Debug\</OutputPath>
    <LangVersion>10.0</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>..\Build\OnigiriConsole\x64-Release\</OutputPath>
    <LangVersion>10.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OnigiriCore\OnigiriCore.csproj" />
    <ProjectReference Include="..\OnigiriPlatform\OnigiriPlatform.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.RollingFile" Version="3.3.0" />
  </ItemGroup>
</Project>